
// DATA TYPES :

// (1) PRIMITIVE DATATYPE: 

// (1) STRING
// (2) NUMBER
// (3) BOOLEAN
// (4) NULL
// (5) UNDEFINED
// (6) SPECIAL CHARRECTER

// (2) NON-PREMITIVE DATATYPE:(REFERENCE DATATYPE)

// (1) ARRAY
// (2) OBJECT
// (3) DATE-TIME


// (1) PRIMITIVE DATATYPE:

// (1) STRING: STRING IS A DATATYPE IN JAVASCRIPT

// HOW TO IDENTIFY STRING OR DENOTE A STRING :

// (1) ""
// (2) ''
// (3) ``

 let a = "arnab"
console.log(a)

// TYPE OF IS A KEYWORD WHICH IS USED TO KNOW THE TYPE OF DATA TYPE


